'use strict';
exports.seed = function (knex, Promise) {
    // Deletes ALL existing entries
    return knex('blog_feeds').del()
        .then(function () {
            // Inserts seed entries
            return knex('blog_feeds').insert([
                {
                    uuid: '2c7be513-9083-439c-937f-42bbe95c0cb9',
                    author: null,
                    description: 'Links for the intellectually curious, ranked by readers.',
                    link: 'https://news.ycombinator.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/hacker-news-2-569388.png',
                    items: null,
                    rss: 'https://news.ycombinator.com/rss',
                    title: 'Hacker News',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '8555fac3-8c0a-42c7-b71a-9ae836a615a9',
                    author: null,
                    description: 'Synthesizer and electronic music news, synth and music software reviews and more!',
                    link: 'http://www.synthtopia.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/press-synthtopia-logo.jpg',
                    items: null,
                    rss: 'http://www.synthtopia.com/feed',
                    title: 'Synthtopia',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '321d2897-f108-45c1-96ca-3aa70ec46590',
                    author: null,
                    description: 'The main page.',
                    link: 'http://www.dailykos.com/blogs/main',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/daily-kos-squarelogo-1517554340259.png',
                    items: null,
                    rss: 'https://feeds.dailykos.com',
                    title: 'Daily Kos',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '9546ff34-ff07-4e31-9332-786ea544ec47',
                    author: null,
                    description: 'A blog about Major League Baseball',
                    link: 'https://www.baseballmusings.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/788443.png',
                    items: null,
                    rss: 'http://feeds2.feedburner.com/Baseballmusingscom',
                    title: 'Baseball Musings',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '2e535aa1-d6d3-4741-9df7-e47ec5ac2260',
                    author: null,
                    description: 'The latest from Bandcamp',
                    link: 'https://daily.bandcamp.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/bc-site-icon1.png',
                    items: null,
                    rss: 'https://daily.bandcamp.com/feed',
                    title: 'Bandcamp Daily',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '3b7cdbfa-751e-4622-85e2-31c17abd351f',
                    author: null,
                    description: 'A community for the awesome MVC JS framework.',
                    link: 'https://www.reddit.com/r/angularjs/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/Z4ki_RNzhlka_Gnb.png',
                    items: null,
                    rss: 'https://reddit.com/r/angularjs/.rss',
                    title: 'angular.js',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'b1c2eff2-81e8-4f19-a1ba-8fff123fb89a',
                    author: null,
                    description: 'A source for news on music that is challenging, interesting, different, progressive, introspective, or just plain weird',
                    link: 'https://avantmusicnews.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/cropped-cropped-amnbanner1.jpg',
                    items: null,
                    rss: 'https://avantmusicnews.com/rss',
                    title: 'Avant Music News',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'b081d79b-ff77-4586-83f3-e9eea5e22c9a',
                    author: null,
                    description: 'The news according to John Marshall',
                    link: 'https://talkingpointsmemo.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/tpm-sq.svg',
                    items: null,
                    rss: 'https://talkingpointsmemo.com/feed/all',
                    title: 'Talking Points Memo',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '5eb65b5e-6896-4357-94af-e48fad7c64cc',
                    author: null,
                    description: 'Wonkette',
                    link: 'https://www.wonkette.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/wonkette.jpg',
                    items: null,
                    rss: 'https://www.wonkette.com/feeds/feed.rss',
                    title: 'Wonkette',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '09689d96-f0fb-4a3e-ad8c-1d71cb9545a8',
                    author: null,
                    description: 'Fostering connections, deepening knowledge, encouraging appreciation, and providing financial support for new music created in the United States',
                    link: 'https://www.newmusicusa.org/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/newmusicbox.png',
                    items: null,
                    rss: 'https://nmbx.newmusicusa.org/rss',
                    title: 'NewMusicBox – NewMusicBox',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '4de05f59-d8df-49a0-9ad7-4cc9b80f15ae',
                    author: null,
                    description: 'New classical music, art, and technology',
                    link: 'https://www.icareifyoulisten.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/TvlOzOKS_400x400.jpg',
                    items: null,
                    rss: 'https://www.icareifyoulisten.com/rss',
                    title: 'I CARE IF YOU LISTEN',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '79f05037-72d3-497e-a57a-54012a79407b',
                    author: null,
                    description: 'Books, articles, and a blog by the music critic of The New Yorker',
                    link: 'https://www.therestisnoise.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/41qc8pZFMcL._SL500_.jpg',
                    items: null,
                    rss: 'https://www.therestisnoise.com/atom.xml',
                    title: 'Alex Ross: The Rest Is Noise',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '009b6c3f-14a2-4add-abc2-4ea3380ae67c',
                    author: null,
                    description: 'Reviews of Free Jazz and Improvised Music',
                    link: 'http://www.freejazzblog.org/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/RQxWDoWr_400x400.jpg',
                    items: null,
                    rss: 'http://www.freejazzblog.org/atom.xml',
                    title: 'The Free Jazz Collective',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'c1979d0e-d388-44ca-8ab0-a41d422c831a',
                    author: null,
                    description: 'The Contemporary Classical Music Community',
                    link: 'http://www.sequenza21.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/seq21logo1.jpg',
                    items: null,
                    rss: 'http://www.sequenza21.com/feed',
                    title: 'Sequenza21/',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '972a2dbc-9441-4c12-a262-e3119559d47d',
                    author: null,
                    description: 'Slate RSS',
                    link: 'https://slate.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/slate.png',
                    items: null,
                    rss: 'https://slate.com/feeds/all.rss',
                    title: 'Slate Magazine',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '08030a4a-4d9c-4003-89cc-872ad78c8d89',
                    author: null,
                    description: 'The latest news from TheHill.com',
                    link: 'https://thehill.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/theHillLogo.png',
                    items: null,
                    rss: 'http://thehill.com/rss/syndicator/19109',
                    title: 'The Hill - The Hill News',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '4c2a61cb-27a2-4c56-805a-8282bcf11221',
                    author: null,
                    description: 'Axios',
                    link: 'https://www.axios.com/top/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/axios-vector-logo.png',
                    items: null,
                    rss: 'http://api.axios.com/feed/',
                    title: 'Axios',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '67063476-7716-49e8-8c10-122989636ccd',
                    author: null,
                    description: 'Smart, fearless journalism',
                    link: 'https://www.motherjones.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/MJ_cropped-favicon-512x512.png',
                    items: null,
                    rss: 'https://www.motherjones.com/politics/feed/',
                    title: 'Politics – Mother Jones',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '67dce9dc-df80-4ce4-8516-cf79f3e2388e',
                    author: null,
                    description: 'Nate Silver’s FiveThirtyEight uses statistical analysis — hard numbers — to tell compelling stories about politics, sports, science, economics and culture.',
                    link: 'https://fivethirtyeight.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/0660d8ba58b80eabbfa60e410d32ed7f.jpg',
                    items: null,
                    rss: 'http://fivethirtyeight.com/politics/feed',
                    title: 'Politics – FiveThirtyEight',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'bb51cad9-ef52-4910-9184-559edd28647f',
                    author: null,
                    description: '"We deal in illusions, man. None of it is true. But you people sit there day after day, night after night, all ages, colors, creeds. We\'re all you know. You\'re beginning to believe the illusions we\'re spinning here. You\'re beginning to think that the tube is reality and that your own lives are unreal. You do whatever the tube tells you. You dress like the tube. You eat like the tube. You even think like the tube. In God\'s name, you people are the real thing, WE are the illusion." -Howard Beale',
                    link: 'https://digbysblog.blogspot.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/network-howard-beal.jpg',
                    items: null,
                    rss: 'http://digbysblog.blogspot.com/feeds/posts/default',
                    title: 'Hullabaloo',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'a10dc8ef-98ec-4b9e-b5f3-3c4705cb13f2',
                    author: null,
                    description: 'Node.js Support, Training and Consulting for the Enterprise, Worldwide',
                    link: 'https://nodesource.com/blog',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/nodesource-512x512.png',
                    items: null,
                    rss: 'https://nodesource.com/blog/rss',
                    title: 'The NodeSource Blog',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'a4e7fedd-46fb-4d9f-9c17-e8593c0c949b',
                    author: null,
                    description: 'Curious Perversions in Information Technology',
                    link: 'http://thedailywtf.com',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/logoWTF.png',
                    items: null,
                    rss: 'http://syndication.thedailywtf.com/TheDailyWtf',
                    title: 'The Daily WTF',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '25243f5e-e861-4252-abc5-ccf7aa5c8f8b',
                    author: null,
                    description: 'Helping you become a better engineer',
                    link: 'https://swizec.com/blog',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/swiz.png',
                    items: null,
                    rss: 'http://swizec.com/blog/feed',
                    title: 'A geek with a hat',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'f9bc3d9c-5960-4fa6-aa28-1b43a01cc73f',
                    author: null,
                    description: 'A blog featuring tutorials about JavaScript, HTML5, AJAX, PHP, CSS, WordPress, and everything else development.',
                    link: 'https://davidwalsh.name/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/dwblogo.png',
                    items: null,
                    rss: 'https://davidwalsh.name/feed',
                    title: 'David Walsh Blog',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '99f6b8cc-dbde-4757-abb3-e46cf6a1ecb1',
                    author: null,
                    description: 'NodeJS Subreddit',
                    link: 'https://www.reddit.com/r/node/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/nodejssubreddit.png',
                    items: null,
                    rss: 'https://reddit.com/r/node/.rss',
                    title: 'node.js',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'e8249664-185f-444e-acd0-20928581bfb8',
                    author: null,
                    description: 'The latest news and tips from the Angular team - Medium',
                    link: 'https://blog.angular.io/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/1_TGH72Nnw24QL3iV9IOm4VA.png',
                    items: null,
                    rss: 'https://blog.angular.io/rss',
                    title: 'Angular Blog - Medium',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'f7fb07b5-11a7-4304-8fd7-9447219717f1',
                    author: null,
                    description: 'An Astutely Savvy Blend of Talent &amp; Opportunity',
                    link: 'http://authenticjobs.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/authenticjobs2-150x150.png',
                    items: null,
                    rss: 'https://authenticjobs.com/rss/fulltime.xml',
                    title: 'AuthenticJobs.com Job Listings - Full-time',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '83cfdddd-a5f7-4f46-b4db-c698f082def7',
                    author: null,
                    description: 'A website powered by alien technology from the future.',
                    link: 'https://catonmat.net/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/catonmat-logo-powered-by-alien-technology.png',
                    items: null,
                    rss: 'https://catonmat.net/feed',
                    title: 'catonmat.net – less is more',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '33ce0ce6-7f8e-4e1a-919e-035719852076',
                    author: null,
                    description: 'Essays, opinions, and advice on the act of computer programming from Stack Overflow.',
                    link: 'https://stackoverflow.blog/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/blog_logos/cropped-SO_Logo_glyph-use-this-one-smaller-32x32.jpg',
                    items: null,
                    rss: 'https://stackoverflow.blog/rss',
                    title: 'Stack Overflow Blog',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'c2f08cfd-3860-490b-b1ed-c3810c800289',
                    author: null,
                    description: 'Online reference, blog and news source for the Web as Platform. Because the world\'s your programmable oyster.',
                    link: 'https://www.programmableweb.com/rss_blog',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/blog_logos/programmableWebPiece.jpeg',
                    items: null,
                    rss: 'https://feeds.feedburner.com/ProgrammableWeb',
                    title: 'ProgrammableWeb',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '017317fd-72bf-411f-a41a-401b4fff5043',
                    author: null,
                    description: 'Scott Hanselman on Programming, User Experience, The Zen of Computers and Life in General',
                    link: 'https://www.hanselman.com/blog/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/blog_logos/tinyheadshot2.jpg',
                    items: null,
                    rss: 'https://hanselman.com/blog/feed',
                    title: 'Scott Hanselman\'s Blog',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'b1ea9fb5-378a-4616-8142-f5db5a953adf',
                    author: null,
                    description: 'Recent content in Articles on Smashing Magazine — For Web Designers And Developers',
                    link: 'https://www.smashingmagazine.com/articles/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/blog_logos/smashing-logo-avatar-opt.png',
                    items: null,
                    rss: 'https://smashingmagazine.com/feed',
                    title: 'Articles on Smashing Magazine — For Web Designers And Developers',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '460065c7-f949-4bbb-9397-8a0b2193baf4',
                    author: null,
                    description: 'CSS Architecture, Web Performance Optimisation, and more, by Harry Roberts',
                    link: 'https://csswizardry.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/blog_logos/cssWizardryLogo.png',
                    items: null,
                    rss: 'https://csswizardry.com/feed',
                    title: 'CSS Wizardry',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '5efd84d8-4155-421e-8f00-eaad72d4ea9d',
                    author: null,
                    description: 'Weekly e-mail roundup of latest CSS articles, tutorials, tools and experiments',
                    link: 'https://css-weekly.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/blog_logos/css_weekly_shirt.png',
                    items: null,
                    rss: 'https://css-weekly.com/feed',
                    title: 'CSS WeeklyCSS Weekly',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '7ff858d2-670f-453b-92fd-51398dd05820',
                    author: null,
                    description: 'Book Recommendations and Reviews',
                    link: 'https://bookriot.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/blog_logos/bookriot.png',
                    items: null,
                    rss: 'https://feeds.feedburner.com/bookriot',
                    title: 'BOOK RIOT',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '88b924d8-f158-4cf6-b3d0-11b0588d35ca',
                    author: null,
                    description: 'Arts and Culture News',
                    link: 'https://www.theparisreview.org/blog',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/blog_logos/theParisReview.png',
                    items: null,
                    rss: 'https://feeds.feedburner.com/TheParisReviewBlog',
                    title: 'The Paris Review',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '0100e49e-c3c5-4420-8fb7-d4b223b6b0a2',
                    author: null,
                    description: 'Timothy McSweeney’s Internet Tendency',
                    link: 'https://www.mcsweeneys.net/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/blog_logos/McS_Logo_stacked_hires-02.jpg',
                    items: null,
                    rss: 'https://feeds.feedburner.com/mcsweeneys',
                    title: 'McSweeney’s',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'f76faa65-0f19-4d6e-bebc-de39568f4745',
                    author: null,
                    description: '',
                    link: 'https://www.nytimes.com/section/books?emc=rss&amp;partner=rss',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/blog_logos/NYTimes-book-review.png',
                    items: null,
                    rss: 'http://www.nytimes.com/services/xml/rss/nyt/Books.xml',
                    title: 'NYT &gt; Books',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '25be2cba-57fe-4371-bc06-ccf8ce1afd49',
                    author: null,
                    description: 'Book World',
                    link: 'http://www.washingtonpost.com/wp-dyn/print/sunday/bookworld?nav=rss_print/sunday/bookworld',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/blog_logos/p412741g.png',
                    items: null,
                    rss: 'http://www.washingtonpost.com/wp-srv/print/sunday/bookworld/rssheadlines.xml',
                    title: 'washingtonpost.com - Book World',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '046a8434-14de-443e-b24c-f4998cf2de80',
                    author: null,
                    description: 'Proudly lowering the level of political discourse',
                    link: 'http://rudepundit.blogspot.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/blog_logos/-uUknLBF_400x400.jpg',
                    items: null,
                    rss: 'http://rudepundit.blogspot.com/feeds/posts/default',
                    title: 'The Rude Pundit',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '8bd35411-98ed-4cf5-8fa5-b416f6ffcfb2',
                    author: null,
                    description: 'Smart, fearless journalism',
                    link: 'https://www.motherjones.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/blog_logos/mother-jones.jpg',
                    items: null,
                    rss: 'http://feeds.feedburner.com/motherjones/feed',
                    title: 'Mother Jones',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '32b76269-7bf8-404f-a857-7afdcb6970d7',
                    author: null,
                    description: 'The Nation Magazine',
                    link: 'https://www.thenation.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/blog_logos/the-nation-logo.png',
                    items: null,
                    rss: 'http://www.thenation.com/feed/?post_type=article',
                    title: 'Article – The Nation',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '22c40084-bac5-4ff5-9f24-fefaabb78e37',
                    author: null,
                    description: 'The New Republic',
                    link: 'https://newrepublic.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/blog_logos/theNewRepublic.png',
                    items: null,
                    rss: 'https://newrepublic.com/pages/rss',
                    title: 'The New Republic',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '3eebc536-dc48-4711-9901-e546f0d73650',
                    author: null,
                    description: '',
                    link: 'https://www.theatlantic.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/blog_logos/the_atlantic_2019_logo.png',
                    items: null,
                    rss: 'https://www.theatlantic.com/feed/all/',
                    title: 'The Atlantic',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'af66bdc7-e46c-43b8-a39c-878d80f01b6b',
                    author: null,
                    description: 'All about the JavaScript programming language!',
                    link: 'https://www.reddit.com/r/javascript/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/5589238-reddit-icon-vector-images-icon-sign-and-symbols-reddit-logo-png-300_300_preview.png',
                    items: null,
                    rss: 'https://reddit.com/r/javascript/.rss',
                    title: '𝚓𝚊𝚟𝚊𝚜𝚌𝚛𝚒𝚙𝚝',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'f99c2c48-c52c-4d9d-8d60-8756a61620a6',
                    author: null,
                    description: 'Learn CSS | HTML5 | JavaScript | Wordpress | Tutorials-Web Development | Reference | Books and More',
                    link: 'https://www.sitepoint.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/58482e76cef1014c0b5e4a6c.png',
                    items: null,
                    rss: 'https://sitepoint.com/feed',
                    title: 'SitePoint',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'fceb9120-e6a1-4be1-bbe5-aef9db874440',
                    author: null,
                    description: 'Where programmers share ideas and help each other grow—A constructive and inclusive social network.',
                    link: 'https://dev.to/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/devtorainbow.png',
                    items: null,
                    rss: 'https://dev.to/feed',
                    title: 'DEV Community',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'cce488c6-e563-4de3-b6bc-266ba896ce61',
                    author: null,
                    description: 'Description pending',
                    link: 'http://www.echojs.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/acdaff17c49fc10cfb43a2e557804099_400x400.png',
                    items: null,
                    rss: 'https://www.echojs.com/rss',
                    title: 'Echo JS',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '03520f1f-b069-4a3d-9329-69451cf9c9e6',
                    author: null,
                    description: 'A free, once–weekly e-mail round-up of Node.js news and articles.',
                    link: 'https://nodeweekly.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/qzlqdaj4qzm2bzcdliyp.png',
                    items: null,
                    rss: 'https://nodeweekly.com/rss/12acdl5j',
                    title: 'Node Weekly',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '6ba1eb91-375b-4d49-b47a-f9661682f9ba',
                    author: null,
                    description: 'Google News',
                    link: 'https://news.google.com/search?q=javascript&hl=en-US&gl=US&ceid=US%3Aen',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/1200px-Google_News_icon.svg.png',
                    items: null,
                    rss: 'https://news.google.com/rss/search?pz=1&cf=all&topic=topics&q=javascript&hl=en-US&num=10&gl=US&ceid=US:en',
                    title: 'Google News - Javascript',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '66a55437-b871-43c3-b420-fb4fd4b3105f',
                    author: 'JSConf',
                    description: '',
                    link: 'https://www.youtube.com/channel/UCzoVCacndDCfGDf41P-z0iA',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/jsconf_eu.png',
                    items: null,
                    rss: 'https://www.youtube.com/channel/UCzoVCacndDCfGDf41P-z0iA',
                    title: 'JSConf',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '2cae1952-92b6-47ba-a071-6c26ffb7bf3b',
                    author: null,
                    description: '',
                    link: 'https://www.dailywritingtips.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/dwt_400x400.gif',
                    items: null,
                    rss: 'https://www.dailywritingtips.com/feed/',
                    title: 'Daily Writing Tips',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '4fab6bab-b9bf-4e30-8ff4-2b2929d624be',
                    author: null,
                    description: 'Writing, self-publishing, book marketing, making a living with your writing',
                    link: 'https://www.thecreativepenn.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/theCreativePenn.jpg',
                    items: null,
                    rss: 'http://feeds.feedburner.com/TheCreativePenn',
                    title: 'The Creative Penn',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'a03e655b-8905-4009-8637-054a3a2781f0',
                    author: null,
                    description: 'The Online Writing Workbook',
                    link: 'https://thewritepractice.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/writePracticeLogo.jpeg',
                    items: null,
                    rss: 'https://thewritepractice.com/feed/',
                    title: 'The Write Practice',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '5b0e0672-1206-476e-86e1-6a5c10cf0eb9',
                    author: null,
                    description: 'about the craft and business of fiction',
                    link: 'https://writerunboxed.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/smaller-jpg-Unconference-e1399854512236.jpg',
                    items: null,
                    rss: 'http://feeds.feedburner.com/WriterUnboxed',
                    title: 'Writer Unboxed',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'e6d6a7ec-ab9a-4b89-a4e3-cb9309e25b22',
                    author: null,
                    description: 'Creative Writing Tips and Ideas',
                    link: 'https://www.writingforward.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/4f6ee35db80d664bb6fb85dfa71e8963.jpg',
                    items: null,
                    rss: 'http://feeds.feedburner.com/WritingForward',
                    title: 'Writing Forward',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'fdb900a9-b8d3-4408-b7f2-f379a468df22',
                    author: null,
                    description: 'The Internet\'s Band of Incorrigible Spitballers® Since 2006',
                    link: 'https://mockpaperscissors.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/dump-trump.jpg',
                    items: null,
                    rss: 'https://mockpaperscissors.com/feed/',
                    title: 'Mock Paper Scissors',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'a56f0791-9ade-4c22-9ef8-564efdaaa4ff',
                    author: null,
                    description: 'Like Kryptonite To Stupid',
                    link: 'https://oliverwillis.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/willis1.jpeg',
                    items: null,
                    rss: 'https://oliverwillis.com/feed/',
                    title: 'Oliver Willis',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: 'd4449a9f-0589-4875-bb7e-daa523666a94',
                    author: 'DownWithTyranny',
                    description: '"When fascism comes to America, it will be wrapped in the flag and carrying the cross." -- Sinclair Lewis',
                    link: 'https://downwithtyranny.blogspot.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/dwtlgob_400x400.jpg',
                    items: null,
                    rss: 'https://downwithtyranny.blogspot.com/feeds/posts/default',
                    title: 'DownWithTyranny!',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        },
                {
                    uuid: '5a271358-a6d3-471a-ba17-30f481d3b98b',
                    author: null,
                    description: 'Music, Film, TV and Political News Coverage',
                    link: 'https://www.rollingstone.com/',
                    image: 'https://habits168-hurdaudio.s3.amazonaws.com/feed_icons/RS_Monogram_3000px-copy-e1530547673203.png',
                    items: null,
                    rss: 'https://www.rollingstone.com/politics/feed',
                    title: 'Politics',
                    created_at: new Date('2019-06-01 17:21:00.000 UTC'),
                    updated_at: new Date('2019-06-01 17:21:00.000 UTC')
        }
      ]);
        });
};
